### ISSUE TITLE
rule applied to structs not struct keys

### ISSUE THREAD

**Issue by sultatos** [hyperjumptech/grule-rule-engine#1]
**Is your feature request related to a problem? Please describe.**
Lets assume we have this rule 
```
rule SpeedUp "When testcar is speeding up we keep increase the speed."  {
    when
        TestCar.SpeedUp == true && TestCar.Speed < TestCar.MaxSpeed
    then
        TestCar.Speed = TestCar.Speed + TestCar.SpeedIncrement;
		DistanceRecorder.TotalDistance = DistanceRecord.TotalDistance + TestCar.Speed;
}
```
 and we have those structs 
```
tc := &TestCar{
    SpeedUp:        true,
    Speed:          0,
    MaxSpeed:       100,
    SpeedIncrement: 2,
}
dr := &DistanceRecorder{
    TotalDistance: 0,
}

tc2 := &TestCar{
    SpeedUp:        true,
    Speed:          0,
    MaxSpeed:       100,
    SpeedIncrement: 2,
}

```
How do i insert all the facts in dataContext and be able to run them with the same rule?
```
dataContext := context.NewDataContext()
dataContext.Add("TestCar", tc)
dataContext.Add("DistanceRecorder", dr)
dataContext.Add("TestCar", tc2)
```
This does not work for me. Am I doing something wrong?
The problem is that i want to have both the facts on DataContext because i may want to later add a new rule that will be applied to both the facts.
As i see it right now the rules apply on the keys and not on the structs

**Comment by newm4n** [comment]
Thank you for your input.
The behaviour you report is an expected behaviour. 
The Rule Engine will process all facts at hand and each fact need to be ID-ed by they key.
If the rule accept "TestCar1" and "TestCar2" fact then thats the way it should be.

If you wish to work with a set of cars, then you can create something like

type Cars struct {
    testCars []*TestCar
}

And add your Cars fact into it. You can provide functions for that structs that can be called from the rule engine to manipulate the cars inside.

I hope this help.

**Comment by sultatos** [comment]
It helped a lot, it would have been great to have a way to fire a rule based on structs and not keys.
