### ISSUE TITLE
Save condition result for use in then clause?

### ISSUE THREAD

**Issue by ikhosravi** [hyperjumptech/grule-rule-engine#12]
Hi,
Is it possible to save a function result in the condition part and pass it to 'then' statement)?
for example, the condition is if the file is found, then I could have its path in then statement rather than calling the same function one more time in 'then' statement.
Thanks in advance

**Comment by newm4n** [comment]
Yes,

All data put in `datacontext` are available in the `when` and `then` clause, but its important to know that when an expression in `when`, when it passes, does not means that the `then` statements will guaranteed to be executed. Because if other rule conflict, the first rule might not get executed as it `salience` is possibly lower than the second.

You can create a fact `struct` and call the function in `when` clause. The function in the struct would look for some file and store it in the struct it self. This makes the information available in the `then` clause. In fact, this information would become available in all other rules.

Another thing is, you don't have to worry if two heavy function get called twice in a single rule evaluation cycle, because they wont be more than 1 invocation. Rete algorithm will ensure that.

```
rule loadFile "Find and load the file when file is not yet loaded" {
      when 
             FileLoader.File == "" 
      then 
             FileLoader.FindAndLoadFile();
}

rule transferAndPurgeFile "If the file is loaded, transfer the file and purge" {
     when 
          FileLoader.File != ""
     then 
          FileTransfer.Transfer(FileLoader.File);
          FileLoader.File = "";
}
```

As you can see, Object in data context is available on both `when` and `then`.

**Comment by ikhosravi** [comment]
thanks, @newm4n for pointing to struct and examples.
I'm looking for this which I think storing in a struct is a good way to do it:

```
rule SearchforFile "If the file is found , delete it" {
     when 
          File.Search('a.txt')
     then 
          File.Delete('path-of-a.txt-')
}
```
