### ISSUE TITLE
Need recommendation on usage

### ISSUE THREAD

**Issue by sombhattacharyya1983** [hyperjumptech/grule-rule-engine#121]
I am currently beginning to evaluate grools for usage in a  decision engine work at my organisation.
In a nutshell we are looking to have some http endpoints to receive data that I am thinking of converting to facts and saving to a database(pgsql).
Thereon we want to load our rules (.grl) and process them against the facts.
Now as an outcome of the inference I want a result to be saved in another table in the same database.

I am trying to understand what part of my flow can integrate grools.
Is there a way to specify the actions in code ?   

Any advice will be helpful.

**Comment by niallnsec** [comment]
I am doing something similar in a work project to what you have described.

In order to make calls out to the database and perform other actions when a rule matches I am taking advantage of the ability to define functions on facts.

There is an example which shows this: https://github.com/hyperjumptech/grule-rule-engine/blob/master/examples/CallingFactFunctionExample_test.go

In that example the function Clap() is defined on the Clapper object. In my code, when I run the engine I always pass in two facts. The first contains the data object I am interested in, and the second is an object called "Helper". The helper object is instantiated by passing in things like the DB connection so I can use it in function calls from within a rule.

For example:

```go
package main

import (
	"context"

	"github.com/hyperjumptech/grule-rule-engine/ast"
	"github.com/hyperjumptech/grule-rule-engine/builder"
	"github.com/hyperjumptech/grule-rule-engine/engine"
	"github.com/hyperjumptech/grule-rule-engine/pkg"
	"github.com/jackc/pgx/v4"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type Helper struct {
	dbConn *pgx.Conn
	ctx    context.Context
	log    *zerolog.Logger
}

type Element struct {
	Id                  int
	SomeInterestingData string
}

func (h *Helper) RaiseAlert(elementId int, code int, message string) {
	_, err := h.dbConn.Exec(h.ctx, "INSERT INTO alerts .....", elementId, code, message)
	if err != nil {
		h.log.Error().Err(err).Msg("Error raising alert for matched rule")
	}
}

const entityRulesGrl = `
rule AlertInterestingEntity "Raise an alert if the entity is interesting" salience 10 {
	when
		Entity.SomeInterestingData == "Interesting"
	then
		Helper.RaiseAlert(Entity.Id, 1234, "Interesting entity!");
}
`

func initDb() *pgx.Conn {
	//perform DB init
}

func main() {
	dbConn := initDb()
	h := &Helper{
		dbConn: dbConn,
		ctx:    context.TODO(),
		log:    &log.Logger,
	}
	e := &Element{
		Id:                  1,
		SomeInterestingData: "Interesting",
	}

	dataContext := ast.NewDataContext()
	err := dataContext.Add("Helper", h)
	if err != nil {
		panic(err)
	}
	err = dataContext.Add("Entity", e)
	if err != nil {
		panic(err)
	}

	lib := ast.NewKnowledgeLibrary()
	ruleBuilder := builder.NewRuleBuilder(lib)
	err = ruleBuilder.BuildRuleFromResource("EntityRules", "0.1.1", pkg.NewBytesResource([]byte(entityRulesGrl)))
	if err != nil {
		panic(err)
	}
	knowledgeBase := lib.NewKnowledgeBaseInstance("CallingFactFunction", "0.1.1")
	eng := &engine.GruleEngine{MaxCycle: 500}
	err = eng.Execute(dataContext, knowledgeBase)
	if err != nil {
		panic(err)
	}
	
	_ = dbConn.Close(context.TODO())
}
```

And of course you can also define functions on the data object itself if that is more convenient. In my case I like to have all the helper functions self contained as I run the engine over multiple different data object types.

The power of the engine becomes even more apparent when you take into account that your rules can modify the fields in your facts, so you can have a series of rules, ordered using the salience values, which transform and then finally store data as it passes through the engine.

For example:
```
rule NormaliseInterestingEntity "Normalise the SomeInterestingData field" salience 10 {
	when
		Entity.SomeInterestingData == "Something interesting"
	then
		Entity.SomeInterestingData = "Interesting";
                 Complete();
}

rule AlertInterestingEntity "Raise an alert if the entity is interesting" salience 20 {
	when
		Entity.SomeInterestingData == "Interesting"
	then
		Helper.RaiseAlert(Entity.Id, 1234, "Interesting entity!");
}
```
The higher priority rule modifies the object, then on the next cycle the lower priority rule picks up the updated value in SomeInterestingData and raises an alert.

I have been using grule for a while now and it has been working great, the only thing I would say is you should always try to instantiate your rule base once and then save it for reuse each time you execute the engine, otherwise you take a significant performance penalty each time grule has to re-parse the ruleset. Once thats done, the actual execution of the engine is incredibly fast.

**Comment by sombhattacharyya1983** [comment]
@niallnsec This is golden ! 
Thank you so much for this information. Highly appreciated. I will try do a quick POC and maybe be run some questions by you if its alright.

**Comment by newm4n** [comment]
Im closing this. Its been 22 days.
