### ISSUE TITLE
decouple rules and evaluations

### ISSUE THREAD

**Issue by rglyons** [hyperjumptech/grule-rule-engine#122]
Hi there!

**Is your feature request related to a problem? Please describe.**
With the release of 1.6.0, we saw the ability to use the same KnowledgeBase for multiple concurrent threads. This was great, since it allowed us to only parse the rule library once, which was a CPU-intensive operation that was bogging down our system previously. After upgrading grule we saw CPU usage reduce significantly. I think it can go further, though.

In my opinion, there are a couple of issues with the current implementation - namely KnowledgeBase **cloning**:
1. cloning still takes CPU cycles, and for our system, which sees potentially millions of events per day, this can add up to quite a bit of CPU usage.
2. cloning takes up quite a bit of memory, and may actually have a memory leak, unless the leak was actually caused by our own code, which is also possible (I didn't profile deep enough to make a strong claim). The point is, cloning takes a non-zero amount of memory per event, and at millions of events per day, the memory allocations are significant.

As far as I understand grule, I don't think cloning KnowledgeBases is necessary at all. A KnowledgeBase can be created and parsed once, say at the time of bootstrapping an application, and then traversed and evaluated as **read only**. This would require the evaluations - the results of the traversal - to be stored **separately** from the rule definitions in the KnowledgeBase.

**Describe the solution you'd like**
Looking at the current code, I see the value of a rule being stored within that rule's type. This ties the rule instance to the evaluation/result instance, and since these are tied, the rule instance must be instantiated (cloned) per evaluation (hence `KnowledgeBase.Clone()`). 

For example, here's the `ExpressionAtom` type, which contains the definition of a rule (or part of a rule), as well as the evaluation result:
```go
// ExpressionAtom AST node graph
type ExpressionAtom struct {
	AstID   string
	GrlText string

	Variable     *Variable
	FunctionCall *FunctionCall
	Value        reflect.Value            // <-- evaluation result

	Evaluated bool                        // <-- evaluation result
}
```

If the evaluation results were kept in a different type, then that type could be instantiated per evaluation. This would be 
- a lot cheaper memory-wise, since rule definitions aren't being copied in memory per execution, and 
- it would save any CPU usage that's lost to cloning a KnowledgeBase.

A couple of ways to maintain results in a separate structure:

**Option  1**
Utilize the unique `AstID` on each rule definition type, and maintain a map of evaluation results that can be instantiated each time a KnowledgeBase is evaluated, e.g. 

```go
type evalResults struct {
	Evaluated       bool
	Value reflect.Value
}

// keep some map[string]*evalResults, and when a rule or partial rule is evaluated, write to this map using AstID as the key
```

One concern here is that this solution may require a `sync.Map` to enable concurrent writes of evaluation results, which could be less performant.

**Option 2**
More of an alternative approach to writes in Option 1, but a `chan *evalResult` could be used in place of a `sync.Map`, like this 
```go
type evalResults struct {
        AstID    string    // <-- add the AstID and pass it along on the channel
	evaluated       bool
	evalValueResult reflect.Value
	evalErrorResult error
}

// when rule is evaluated
evalResultsChannel <- &evalResult{ AstID: myAstID, ... }

// in some result collection routine
for _, evalResult := range evalResultsChannel {
    resultsMap[evalRules.AstID] = evalResult
}
```

This avoids any slowdown from a `sync.Map`, but result writes become async, so it's hard to know when a rule's evaluation result is formally stored in the `resultsMap`.

These are just a couple of ideas off the top of my head; there may be better solutions!

Is this decoupling of rule definition and evaluation result possible? Thanks in advance!

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by rglyons** [comment]
I also just dug a bit deeper into the DataContext that's passed into `engine.Execute()` as well. It looks like something similar to the above proposal is already being done for variable assignment within the execution of a KnowledgeBase.

```go
// DataContext holds all structs instance to be used in rule execution environment.
type DataContext struct {
	ObjectStore         map[string]interface{}    // <-- variables written to and read from this map
	Retracted           []string
	VariableChangeCount uint64
}
```

Can something similar be used to read/write all evaluation results to achieve the above proposal?

**Comment by niallnsec** [comment]
Hey,

I was having a look at the code and wondered, do you think having some kind of reset capability would achieve your goal? So rather than cloning the whole KB you would reset all of the contextual data stored in it. That way you could instantiate one KB instance per concurrent goroutine and then reset it each time you are done with it.

I could think of two ways of doing that, either by having an explicit reset function (this could be a bit heavy still) or by changing the logic so the Evaluated bool becomes a uint64 and is incremented on each cycle to indicate the "age" of the evaluation. A similar marker could be kept in the WorkingMemory structure and if an evaluation is outdated it would be automatically re-evaluated.

**Comment by rglyons** [comment]
> That way you could instantiate one KB instance per concurrent goroutine and then reset it each time you are done with it.

So if I understand correctly, you're proposing that I 
1. clone a KB instance for each routine in a pool of long-running goroutines
2. in each routine in this pool, synchronously execute the engine on that KB clone and then reset the evaluation context in preparation for the next engine execution

I see a couple of issues with this approach:
1. I need to maintain a static pool of goroutines that each have something keeping them alive. I'd much rather spawn routines freely and on-demand to execute the engine on some common KB. This will be less complex to implement and do less listening/blocking (which takes up CPU cycles as well), and it would likely scale better as well, since the pool would have to be some pre-determined number of routines that could get maxed out under high or unexpected load. 
2. we still require N copies of the KB for N worker routines, when we could require just one copy of the KB (the original)

Did I understand you correctly or were you proposing something else?

**Comment by niallnsec** [comment]
That is essentially what I was getting at. The most import part was the concept of a reset on the knowledge base object. Since writing the comment above I kept thinking this kind of reset was already implemented and after looking at the code again it seems it is. The engines Execute function is resetting the WorkingMemory which is clearing the Evaluated fields where appropriate. 

I would assume that the time taken to clone a KB is largely a result of instantiating so many new Go objects and looping over the various maps and arrays.

Depending on how your application is structured, it may be more convenient to implement a simple pool of knowledge bases instead of a pool of goroutines. In my application I have a goroutine pool which is continuously processing incoming work objects which is why I went to the goroutine pool approach first, but a KB pool approach would work equally well. I imagine you would have a channel containing "available" KBs and then a "Get" function which would pull from the channel if available or Clone a fresh instance up to a defined limit before blocking. So the pool would grow to suit your workload and persist for as long as necessary.

This would scale well as you could easily implement dynamic up and down scaling of the pool depending on the amount of work being performed. The only significant cost would be in terms of memory, but you are likely looking at something in the order of a few MB or RAM scaling linearly with the size of your rule base.

If you wanted to completely make KB read only though, that seems like it would be challenging since the places where you would need to obtain the state information are in the hottest codepaths in the engine, so performance is key. Not only that but I am also not sure how you pass down the context to deep structures like Expression which currently have no access to the WorkingMemory or KnowledgeBase structures.

In a long running application, I would be very surprised if the performance hit of having to repeatedly acquire context information in the AST graph would not significantly outweigh the performance hit of doing the necessary cloning to fill an appropriately sized pool and then letting the engine reset the working memory the way it currently is.

P.S. If you are experiencing performance issues with the 1.6.0+ codebase it could be due to an apparent goroutine leak in the ExecuteContext function (which is also being called by Execute). I have submitted a PR to fix the issue (#123).

**Comment by rglyons** [comment]
> The engines Execute function is resetting the WorkingMemory which is clearing the Evaluated fields where appropriate.

So I see [here](https://github.com/hyperjumptech/grule-rule-engine/blob/81171ea5a2e4699b622e1b4eb962974c6f7a047e/ast/WorkingMemory.go#L302) what is being cleared on each engine execution of a KnowledgeBase. Only the `expressionSnapshotMap` and the `expressionAtomSnapshotMap` are getting their contents "cleared" by marking `Evaluated = false`. So if I ignore the `Evaluated` fields, I'll assume that only the `Expression.Value` and `ExpressionAtom.Value` fields within the `KnowledgeBase.WorkingMemory` are keeping the KnowledgeBase from becoming 100% read only. 

> the places where you would need to obtain the state information are in the hottest codepaths in the engine, so performance is key

Is there any state information that would need to be obtained in these hot codepaths other than the `Expression.Value` and the `ExpressionAtom.Value`? If these are the only pieces of state info that need to be obtained, they can be stored in a separate map that can be instantiated per engine execution. Reads on this map should be very fast, and they don't even need to be mutex protected _assuming_ only one routine will be writing a result to such a result map at a time. 

It seems like `Expression`s and `ExpressionAtom`s only evaluate one piece at a time, which means only one write to this results map will happen at a time, which means no mutexes or concurrency protection around a result map is necessary. As for higher-level constructs that call `Expression.Evaluate` - are those ever parallelized, or is only one `Expression` evaluated at a time? It seems like the latter is the case as the code is currently written. 

The above things considered, a lockless map should be safely usable for storing `Expression.Value` and `ExpressionAtom.Value`. The perf impact in one evaluation would likely be very small (a map lookup vs a struct field read), but such a change would allow for much higher/cleaner concurrency, which has many more benefits imo. 

> I am also not sure how you pass down the context to deep structures like Expression which currently have no access to the WorkingMemory or KnowledgeBase structures.

The WorkingMemory is already being passed into the `Evaluate` method for both `Expression` ([here](https://github.com/hyperjumptech/grule-rule-engine/blob/81171ea5a2e4699b622e1b4eb962974c6f7a047e/ast/Expression.go#L223)) and `ExpressionAtom` ([here](https://github.com/hyperjumptech/grule-rule-engine/blob/81171ea5a2e4699b622e1b4eb962974c6f7a047e/ast/ExpressionAtom.go#L115)). Are there other places where the WorkingMemory needs to be passed in for these types?

**Comment by niallnsec** [comment]
Thanks for pointing out the WorkingMemory being passed as parameters, I was looking at the structure and completely missed it!

So I can now see how you would implement a solution with a decoupled state since you could pass it down either as a separate parameter or inside of another object, I appreciate the detailed explanation.

I am still very skeptical about the performance of a map in this situation. Maps are a relatively slow data structure when they get to a decent size. In practice, I have noted serious performance issues in accessing maps when entry counts start going above as little as 1024 entries. If I were to take a ruleset with say 5,000 rules, and each rules has an average of 6 expressions, would the state map not now have to be keeping track of 30,000 structs containing potential state information for each item, all of which have to be allocated and indexed into the map?

To answer your update, because the engine might run multiple times over a single Execute request, the evaluation results serve as a cache to speed up the subsequent iterations. It saves having to evaluate identical expressions potentially hundreds of times in a single execution request.

**Comment by newm4n** [comment]
@rglyons & @niallnsec ,
I am very happy to see this discussion happening, showing the interest and comprehension of this project.
I just want to add some explanation into the context of discussion.

The `WorkingMemory` primary purpose is to make sure that `Expression` and `ExpressionAtom` are not duplicated throughout the rules. It very important for the `RETE` algorithm to work. I hope my explanation [here](https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/RETE_en.md#why-rete-algorithm-is-necessary) is clear enough about RETE.

The `WorkingMemory` records `Variable`, `Expression`, `ExpressionAtom` *signatures* and put them into map.
```go
type WorkingMemory struct {
	Name                      string
	Version                   string
	expressionSnapshotMap     map[string]*Expression
	expressionAtomSnapshotMap map[string]*ExpressionAtom
	variableSnapshotMap       map[string]*Variable
	expressionVariableMap     map[*Variable][]*Expression
	expressionAtomVariableMap map[*Variable][]*ExpressionAtom
	ID                        string
}
```

The function `AddExpression(exp *Expression) *Expression` and `AddExpressionAtom(exp *ExpressionAtom) *ExpressionAtom` and `AddVariable(vari *Variable) *Variable` are called by the Builder as each of the AST node (Variable, Expression and ExpressionAtom) get parsed from GRL. We create a kind of `snapshot` for each of those AST node, a signature so we can  deep-compare between node ensuring no duplicates. In each of the method, you can clearly see if the signature exist in the map, we just return the node in the map, if not, we insert the node into the map.

In my opinion, up until that, we can say that WorkingMemory is used only during the parsing proses. But then we know that each of these AST node would have `value`. At the documentation about RETE I mentioned above, an expression atom that contains, for example, a heavy function should not be called again-and-again. The first function invocation is enough to set the expression atom's value, and `Evaluated = true`. Subsequent invocation should only need to return this value. Unless the function have variable argument which those variable are changed (along the execution of the rule). If this argument variable change, this makes the function eligible for re-execution (`Evaluated = false`). 

Thus you can see the `expressionVariableMap` and `expressionAtomVariableMap` come to play in the `WorkingMemory`, to map which `Expression` and `ExpressionAtom` have the `Variable`.  When a Variable AST node get changed (through assignment in the `THEN` scope, we look into an array of `Expression` and `ExpressionAtom` that contains it, and change their `Evaluated` to `False` so it get reevaluated next time.

Reading the concern from @rglyons , I think, we can move the `Value` and `Evaluated` variable from all `Expression` and `ExpressionAtom` AST Node into a Map object somewhere. And have the AST Node to look to this map for their Value or Evaluated. This will make the Cloning un-necessary. BUT, as @niallnsec mentioned, the map have to be very very high performant, as all `Expression`, `ExpressionAtom` AST node will use this map for looking up for values and states.

Still, its easier to create a new map with default values, compared to have to clone the entire KnowledgeBase + WorkingMemory. I get that. Then, as I write this, comes to mind that, since One KnowledgeBase called by multiple thread, mutex would be needed to ensure thread safety. I fear this could bite us back later. This would not be an issue if we have a complete different instance of KnowledgeBase for each execution. What do you think ?

**Comment by rglyons** [comment]
> now have to be keeping track of 30,000 structs containing potential state information for each item, all of which have to be allocated and indexed into the map

This is true - there are extra costs in implementing this decoupling with a map. Namely, the extra costs in memory come from the map internals and extra structures, and the extra costs in CPU come from reading and writing to the map.

I did some calculations, and here's what I came up with. I used your example of 30k Expressions, and then I used a more dramatic 1M Expression example. It's a lot to look at, but I figured numbers would help us reach the best decision 👍🏻.

### memory
**30k Expressions/ExpressionAtoms**
~11MB extra space required per engine execution
```
------------------------ MAP SIZE ------------------------------
INFO[0000] size of map                                   size=11760048 sizeKB=11484.421875 sizeMB=11.215255737304688
----------------------- STRUCT SIZE ----------------------------
INFO[0000] size of structs                               size=750000 sizeKB=732.421875 sizeMB=0.7152557373046875
```
**1M Expressions/ExpressionAtoms**
~350MB extra space required per engine execution
```
------------------------- MAP SIZE ------------------------------
INFO[0012] size of map                                   size=392000048 sizeKB=382812.546875 sizeMB=373.8403778076172
----------------------- STRUCT SIZE ----------------------------
INFO[0012] size of structs                               size=25000000 sizeKB=24414.0625 sizeMB=23.84185791015625
```
Note that the `STRUCT SIZE` is actually just the cumulative size of the Value and Evaluated fields on each Expression/ExpressionAtom, while the `MAP SIZE` is the map overhead + the size of each value in the map, where each value is a struct containing the Value and Evaluated fields, i.e.
```go
type eval struct {
	Value     reflect.Value
	Evaluated bool
}
```
The values in the map _could_ just be `reflect.Value`, where their presence in the map could be used in place of an `Evaluated` field, which could reduce the map size slightly to 
```
INFO[0011] size of map                                   size=328000048 sizeKB=320312.546875 sizeMB=312.8052215576172
```
Another important thing to note here is that this change eliminates the need for KnowledgeBase cloning, so any memory used there is saved and should be considered in the total difference in memory usage when storing evaluation results in a map. The size of 30k Expression structs is 3MB and 1M Expressions is ~100MB, and that doesn't include all other KnoweldgeBase internals that are being copied into memory with each clone. When cloning, that memory is reserved even when the application is idle, so any other application running on the same compute resources that would like to use that memory cannot use it, even if the engine is not executing. This is a huge issue with the cloning solution.

### CPU time
all numbers are ns

**30k Expressions/ExpressionAtoms**
median difference, or difference between (median read time + median write time): 
(207-80) + (343-98) = 372ns per value, mult by 30k values = 11.16ms additional time per execution

max difference, or total difference in reads and writes between min and max values:
(31485-71) + (2005-78) = 33341ns per value, mult by 30k values = 1s additional time per execution (absolute worst case perf degredation)
```
map generated (size: 30000)

field write time samples: 1000
map write time samples: 1000
---------------------- MAP WRITES ------------------------------
min: 103
Q1: 173.5
Q2: 207
Q3: 325
max: 31485
avg: 432.743
mode: [200 205]
--------------------- STRUCT WRITES ----------------------------
min: 71
Q1: 77
Q2: 80
Q3: 82
max: 825
avg: 83.83
mode: [80]

field read time samples: 1000
map read time samples: 1000
----------------------- MAP READS ------------------------------
min: 186
Q1: 291
Q2: 343
Q3: 389
max: 2005
avg: 361.293
mode: [291]
---------------------- STRUCT READS ----------------------------
min: 78
Q1: 87
Q2: 98
Q3: 148.5
max: 980
avg: 118.73
mode: [86]
```

**1M Expressions/ExpressionAtoms**
median difference, or difference between (median read time + median write time): 
(304.5-83) + (730-261) = 690.5ns per value, mult by 1M values = 690.5ms additional time per execution

max difference, or total difference in reads and writes between min and max values:
(22393-71) + (1729-165) = 23886ns per value, mult by 1M values = 23.86s additional time per execution (absolute worst case perf degredation)
```
map generated (size: 1000000)

field write time samples: 1000
map write time samples: 1000
---------------------- MAP WRITES ------------------------------
min: 120
Q1: 221
Q2: 304.5
Q3: 485.5
max: 22393
avg: 656.8
mode: [216]
--------------------- STRUCT WRITES ----------------------------
min: 71
Q1: 80
Q2: 83
Q3: 100
max: 4266
avg: 103.697
mode: [82]

field read time samples: 1000
map read time samples: 1000
----------------------- MAP READS ------------------------------
min: 491
Q1: 669.5
Q2: 730
Q3: 806
max: 1729
avg: 748.057
mode: [729]
---------------------- STRUCT READS ----------------------------
min: 165
Q1: 250
Q2: 261
Q3: 270
max: 495
avg: 264.874
mode: [261]
```
again, if the values in the map _could_are just `reflect.Value`s, this cpu time will decrease.

The best context in which the CPU times can be used is in % slowdown against the existing engine execution, however I can't compute the time it takes for the current codebase to evaluate a 30k/1M Expression KnowledgeBase at the moment. Considering the worst case performance degredation of ~24s in my study, you could say this isn't a feasible solution, but the other solution is to clone a KnowledgeBase with 1M Expressions in memory for concurrency, and I can't imagine that's very feasible.

Thoughts on the above numbers?

I've attached the program I used to get these numbers as well, in case you'd like to take a look.
[scratch_59.go.zip](https://github.com/hyperjumptech/grule-rule-engine/files/5425495/scratch_59.go.zip)

> the engine might run multiple times over a single Execute request, the evaluation results serve as a cache to speed up the subsequent iterations

So it sounds like the subsequent cycles in the engine execution already look up the evaluation results in a map - this doesn't need to change, so there's no loss of performance here with this proposal. 

So the major potential performance loss lies in the first cycle of the engine execution, correct?

**Comment by rglyons** [comment]
@newm4n ,

When you say
> since One KnowledgeBase called by multiple thread, mutex would be needed to ensure thread safety.

a clarifying question comes to mind: Is thread safety needed on a KnowledgeBase if the KnowledgeBase is used in a **read only** manner? Shouldn't thread safety only be required for any values that are being written?

As I understand it, only the `WorkingMemory`, `Expression.Value/Evaluated`, and `ExpressionAtom.Value/Evaluated` need to be written when `engine.Execute` is called. So, if the WorkingMemory is separated from the KnowledgeBase and instantiated per thread, along with the `Value/Evaluated` fields being moved to a separate map or structure that is also instantiated per thread, then the KnowledgeBase needs no thread safety. Writes will only happen within the context of a thread to variables/structures that are instanced to that thread. 

Is that correct?

**Comment by newm4n** [comment]
The KnowledgeBase houses  the AST tree. And obviously it reads and changes context's values. Its not ONLY reading data context. When we have this map to store all the Expression and ExpressionAtom's state, its even more obvious that the knowledge base will read/write the map. 

The singleflight pattern [HERE](https://godoc.org/golang.org/x/sync/singleflight) seems inline with your idea of having singleton to serve multiple requests that give SAME result. But it won't work and dangerous for process that have underlying data manipulation.
