### ISSUE TITLE
I encountered a bug like ”interface conversion: interface {} is *ast.Expression, not *ast.ExpressionAtom“

### ISSUE THREAD

**Issue by chanyaw** [hyperjumptech/grule-rule-engine#145]
**Describe the bug**
I check log
error like this ”interface conversion: interface {} is *ast.Expression, not *ast.ExpressionAtom“

**Expected behavior**
how this error occur ？ 

`// NewID will create a new unique ID string for this runtime.
// Uniqueness between system or apps is not necessary.
func NewID() string {
	MS := time.Now().Unix()
	if lastMS == MS {
		offset++
		return fmt.Sprintf("%d-%d", lastMS, offset)
	}
	lastMS = MS
	offset = 0
	return fmt.Sprintf("%d-%d", lastMS, offset)
}`

I think this code  has concurrency control problems

I look forward to reply

**Comment by newm4n** [comment]
I don't see the relevance between interface casting into *ast.ExpressionAtom with the unique.NewID() function.
NewID only called when creating AST Node and called sequentially by ANTLR4 parser. I hardly doubt the NewID() function will cause concurrency problem and causing the casting error.

However, the error you mention really intrigue me. Could you provide an example GRL that could reproduce the error ?

**Comment by chanyaw** [comment]
> I don't see the relevance between interface casting into *ast.ExpressionAtom with the unique.NewID() function.
> NewID only called when creating AST Node and called sequentially by ANTLR4 parser. I hardly doubt the NewID() function will cause concurrency problem and causing the casting error.
> 
> However, the error you mention really intrigue me. Could you provide an example GRL that could reproduce the error ?

This error caused here

![image](https://user-images.githubusercontent.com/23734944/101729125-9a4a7680-3af2-11eb-982e-a0d593a52bfb.png)

if  astID is the same ， cloneTable will get wrong expression 

I encountered this error online，but I unable to reproduce offline

**Comment by newm4n** [comment]
I see it now, you suspected that the `Expression` and `ExpressionAtom`'s `AstID` possibly got duplicated between them that makes cloneTable.Records['expr.AstID'] returns an `Expression` instead of `ExpressionAtom`. I got it, although Its sounds most unlikely but it might possible. That causes it difficult to reproduce.

In the new patch v1.7.2,  I added `mutex` to make sure that function `NewID()` is thread/concurrent safe. If that the case, I hope your issue won't appear again. 

Thanks a lot.
