### ISSUE TITLE
question: Does the function called in "then" scope be remembered by grule?

### ISSUE THREAD

**Issue by TeCHiScy** [hyperjumptech/grule-rule-engine#153]
As stated in http://hyperjumptech.viewdocs.io/grule-rule-engine/RETE_en/
1. Grule will try to remember all of **the Expression** defined within rule's **when scope** of all rules in the KnowledgeBase.
2. While Grule will try to remember any variable it evaluate within the **when and then scope**, if you change the variable value from outside the rule engine, for example changed from within a function call, Grule won't be able to see this change, thus Grule may mistakenly evaluate a variable which already changed.

According to my understanding, the concept of "expression" includes both variable & function calls (more precisely, AST node). But I'm confused that: 
1. **only expressions in "when" scope are cached** or **expressions in both "when" scope and "then" scope** are cached?
2. If I have two function calls: **myfunc("A")**, **myfunc("B")**, do they share the same cache? More deeply, if I use Changed(\"myfunc("B")\");, will grule clear the cache of **myfunc("A")**?
3. If function calls in "then" scope do cached, then is this necessary? In my situation, I need to call a function with same args mutiple times, in the "then" scope, but I find that the function will be called only once.

**Comment by newm4n** [comment]
To answer your question. 

1. Both. All expression and expression atom values will be cached on the first evaluation on EACH cycle (yes, next evaluation cycle, grule will forget all). All expression yield a value (except for assignment). A Variable have value, Constants have value, Function call have value, Math operation have a resulting value, Logical operation have a resulting value. All this values are cached and remembered. All those expressions (and expression atoms) will be remembered for their value the first time get evaluated. That's one of the main purpose of RETE, why ? because evaluation is/could be an expensive operation.
2. No. Function Expression is uniquely identified by their function name and signatures (the argument sets within, not only argument type though).  myfunc("A") and myfunc("B") is definitely seen as two different function, so their value will have a different cache. Forgetting one, will not forget the other. If you want to forget both, use the function name. Like `Changed("myfunc")` without the argument. 
3. Yes, the expression in `then` scope are also cached (with exception with the assignment expression), but all other sub-expression will be cached for their initial evaluated value. What you experience, when function(s) only called once is fully as expected. When you call a function once, grue will remember the return value and simply return the remembered value instead of re-evaluating the function call. Because function/expression could be very heavy and could kill the engine. Thus, you have to explicitly tell the engine to "Forget" an expression or variable so they can get called again next time.

However, grule will try it best to automatically reset/forget expression whenever necessary without any rule-author's effort.

For example

```text
when
      myFuncIsTrue(fact.X)   // <--- variable fact.X is cached AND return value of function myFuncIsTrue(fact.X ) is cached.
     && fact.X == 4           //  <--- fact.X == 4 boolean result is cached.
then
      fact.X= 10; // since variable fact.X is changed,  this will make all expression related variable fact.X will be forgotten. 
                        // which includes:
                        //      fact.X    <-- the variable it self
                        //       myFuncIsTrue(fact.X )  <-- the function that uses fact.X as argument and
                        //      fact.X == 4  <-- operations (math or logical) that involves fact.X
                        // so nextime, these expression will be re-evaluated.
}
```

**Comment by TeCHiScy** [comment]
Thanks a lot for the detailed explanation, cheers
