### ISSUE TITLE
Issue calling function in Then statement.

### ISSUE THREAD

**Issue by davedbase** [hyperjumptech/grule-rule-engine#155]
**Describe the bug**
Trigger value function isn't set when calling function directly, but works when triggering property.

**To Reproduce**

Run the following code:

```go
package main

import (
	"fmt"
	"time"

	"github.com/hyperjumptech/grule-rule-engine/ast"
	"github.com/hyperjumptech/grule-rule-engine/builder"
	"github.com/hyperjumptech/grule-rule-engine/engine"
	"github.com/hyperjumptech/grule-rule-engine/pkg"
)

const (
	rule3 = `
		rule SampleRule "test"  salience 10 {
			when
				MyMine.Triggered() == true && MySwitch.Triggered() == false
			then
				MySwitch.Flip();
		}
	`
)

// Fact identifies a general fact value
type Fact interface {
	Name() string
}

// Mine defines a special mine variable
type Mine struct {
	Fact
	Name        string
	Description string
	UpdatedAt   time.Time
	Value       bool
}

// GetName gets the value of the switch
func (m Mine) GetName() string {
	return m.Name
}

// Triggered gets the value of the switch
func (m Mine) Triggered() bool {
	return m.Value == true
}

// NewMine generates a new mine type
func NewMine(name string, description string, value bool) (fact *Mine) {
	fact = &Mine{
		Name:        name,
		Description: description,
		Value:       value,
		UpdatedAt:   time.Now(),
	}
	return
}

// Switch defines a special switch variable
type Switch struct {
	Fact
	Name        string
	Description string
	UpdatedAt   time.Time
	Value       bool
}

// GetName gets the value of the switch
func (s Switch) GetName() string {
	return s.Name
}

// Triggered gets the value of the switch
func (s Switch) Triggered() bool {
	return s.Value == true
}

// Flip sets the value of the switch
func (s Switch) Flip() {
	if s.Value == true {
		s.Value = false
	} else {
		s.Value = true
	}
}

// NewSwitch generates a new mine type
func NewSwitch(name string, description string, value bool) (fact *Switch) {
	fact = &Switch{
		Name:        name,
		Description: description,
		Value:       value,
		UpdatedAt:   time.Now(),
	}
	return
}

func main() {
	fact1 := NewMine("MyMine", "This is a sample mine", true)
	fact2 := NewSwitch("MySwitch", "This is a sample switch", false)
	dataContext := ast.NewDataContext()
	err := dataContext.Add(fact1.GetName(), fact1)
	err = dataContext.Add(fact2.GetName(), fact2)
	if err != nil {
		fmt.Println(err)
	}

	lib := ast.NewKnowledgeLibrary()
	ruleBuilder := builder.NewRuleBuilder(lib)

	err = ruleBuilder.BuildRuleFromResource("Test", "0.1.1", pkg.NewBytesResource([]byte(rule3)))
	kb := lib.NewKnowledgeBaseInstance("Test", "0.1.1")
	eng1 := &engine.GruleEngine{MaxCycle: 10}
	fmt.Println(fact2)
	err = eng1.Execute(dataContext, kb)
	fmt.Println(fact2)
}

```

**Expected behavior**
The engine should properly toggle the value of MySwitch to true.

**Additional context**
If you change the rule so that:

```
rule SampleRule "test"  salience 10 {
	when
		MyMine.Triggered() == true && MySwitch.Triggered() == false
	then
		MySwitch.Value = true;
}
```
Then you get the expected result. Note that I'm look at the value of the print before and after the execute statement at the bottom. Also oddly I'm seeing Max cycle reached being hit as well. Here's my output:

```
&{<nil> MySwitch This is a sample switch 2020-12-27 18:16:45.359923 -0500 EST m=+0.001816840 false}
ERRO[0000] Max cycle reached                             lib=grule-rule-engine package=engine
&{<nil> MySwitch This is a sample switch 2020-12-27 18:16:45.359923 -0500 EST m=+0.001816840 true}
```

I don't believe I'm doing anything incorrectly, if so I apologize in advance.

**Comment by TeCHiScy** [comment]
"Max cycle reached" makes sense. 

If I understand your question correctly,
It's because the engine runs your rule 10 times (which is the max cycle), so your "switch" was filpped again and again.
Try to add Retract("SampleRule"); to your then statement.

More deep, please refer to http://hyperjumptech.viewdocs.io/grule-rule-engine/Function_en/, the "Retract" function.

**Comment by TeCHiScy** [comment]
There's two problem.

1. Your `Flip` method has a value receiver `s Switch`, so that `s.Value = false` only changes the copy of a switch, try to use pointer receiver `s *Switch` instead.
2. Since `Flip` method doesn't really change the value of the original "switch", the condition `MyMine.Triggered() == true && MySwitch.Triggered() == false` is satisfied in every rule engine cycle, so the engine runs your rule for up to 10 times, which causes "Max cycle reached". Try to add Retract("SampleRule"); to your then statement if you want your rule to be ran only once. Refer to http://hyperjumptech.viewdocs.io/grule-rule-engine/Function_en/, the "Retract" function.
3. If you directly set the value as `MySwitch.Value = true`, it took effect because the fact you pass to the engine is a pointer, so the engine can change the original "switch".

Hope this will help you.

**Comment by newm4n** [comment]
This is expected behavior.
In your rule...

```go
const (
	rule3 = `
		rule SampleRule "test"  salience 10 {
			when
				MyMine.Triggered() == true && MySwitch.Triggered() == false
			then
				MySwitch.Flip();
		}
	`
)
```

MySwitch.Flip() changes the internal value which is not visible by the engine.
The engine only know and remember 
1. `MyMine.Triggered()`
2. `MySwitch.Triggered()`
3. and `MySwitch.Flip()`

When these functions get called the first time, the engine will remember the return value. The subsequent call to the function, the engine will return the last return value it remembered.  To make the engine forget about a function return value, you could use `Changed` or `Forget` function.

```go
const (
	rule3 = `
		rule SampleRule "test"  salience 10 {
			when
				MyMine.Triggered() == true && MySwitch.Triggered() == false
			then
				MySwitch.Flip();
 				Forget("MySwitch.Triggered()");
 				// or                           
 				// Changed("MySwitch.Triggered()");
 				// Changed or Forget function will force the engine to re-evaluate the function and refresh
 				// its memory about the function.
 				// as of 1.7.0, Changed function is deprecated.

 				Forget("MySwitch.Flip()"); // again, to make sure next time this rule is selected 
 				// the engine will call MySwitch.Flip() function. Not just returning the remembered return value.
		}
	`
)
```

**Comment by davedbase** [comment]
Aha. @TeCHiScy yeah sorry I thumbed revising the example and forgot the pointer change.

@newm4n thanks for the great clarification! That totally makes sense re: the caching mechanic. I'm adjusted my example to account for this and it's working great now!

I'm new to rule engine's (as of a week) so these concepts are very different to me. Fantastic work on this project, it's so flexible! My next step is to figure out how to properly ingest a GruleJSON structure. I'll be storing my rules as JSONB in the database so trying to find a way to bring them into the engine directly.

I appreciate the quick response on this!
