### ISSUE TITLE
[Proposal] Is there any way to add a rule/s to existing knowledgebase ?

### ISSUE THREAD

**Issue by jinagamvasubabu** [hyperjumptech/grule-rule-engine#168]
**Is your feature request related to a problem? Please describe.**
Currently my application is using grule-rule-engine and its working perfectly fine. Thanks @newm4n this is a great work !!!!
Coming to the implementation, i am saving all my rule DSL's in DB (postgres) and pulling them when the container boot up and create a new knowledgeBase and keep it in Memory. so far all fine. let's suppose if someone creates a new rule or rules then i need to pull all the rules again and recreate the knowledgeBase and this is a heavy process even though i know that there are no changes to the existing knowledgeBase except new rules i have to add to the existing knowledgeBase.

**Describe the solution you'd like**
What i am proposing is, when a new rule or rules are created i should be having a way to update the existing knowledgeBase with new rule instead of reloading all the N rules instead of creating a new knowledgeBase instance everytime with all the rules. 

I can contribute on this, just that i need some ideas or pointers from you to implement this feature :)

**Additional context**
Let me know if you need more info

**Comment by newm4n** [comment]
Hm... its been a while. Let me check this ASAP, as far as I can remember, you can easily create/remove RuleEntry in knowledgebase. I will check ASAP I can get to my PC.

**Comment by jinagamvasubabu** [comment]
Thanks for the quick reply

yes i see `AddRuleEntry` and `RemoveRuleEntry` for `knowledgeBase.go`. I am able to add/remove a rule entry to the existing knowledgeBase.


Example:
```go
	rule4 = `
rule AgeNameCheck3 "test 2"  salience 10{
    when
      Pogo.Compare(User.Name, "Vasu")  
    then
      User.Name = "Success vasu";
      Log(User.Name);
      Retract("AgeNameCheck");
}
`

	is := antlr.NewInputStream(rule4)
	lexer := parser.Newgrulev3Lexer(is)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	var parseError error
	errCall := func(e error) {
		parseError = e
	}

	listener := antlr2.NewGruleV3ParserListener(kb, errCall)

	psr := parser.Newgrulev3Parser(stream)
	psr.BuildParseTrees = true
	antlr.ParseTreeWalkerDefault.Walk(listener, psr.Grl())

	grl := listener.Grl
	for _, ruleEntry := range grl.RuleEntries {
		kb.RemoveRuleEntry(ruleEntry.RuleName)
		err := kb.AddRuleEntry(ruleEntry)
		if err != nil && err.Error() != "rule entry TestNoDesc already exist" {
			fmt.Printf("warning while adding rule entry : %s. got %s, possibly already added by antlr listener", ruleEntry.RuleName, err.Error())
		}
	}

	kb.WorkingMemory.IndexVariables()
```
where kb is the existing knowledgebase.

Yes the above code is working fine for me to add a rule entry (removing it first for safer side). Let me  know is this a right way to do ?

**Comment by newm4n** [comment]
Well I'm correct. You can always add or remove `RuleEntry` from `KnowledgeBase`
So if you store your rule entries in database, you should be able to identify which of the rule entry is modified, added or removed.

## Adding additional `RuleEntry`-es to an already existing `KnowledgeLibrary`

If a rule entry is added, you simply build __only__ the added Rule's GRL, the other rule already in the knowledge base do not need to be included in the GRL. After parsing the GRL, the listener will add all new GRL's into knowledge base.
You can see the [logic here](https://github.com/hyperjumptech/grule-rule-engine/blob/436f654cf4accfe35dc9e06808820775cc3e00ee/antlr/GruleParserV3Listener.go#L90)

When you start your server, you build your rule using new KnowledgeLibrary

```go
	mylib := ast.NewKnowledgeLibrary()
	rb := builder.NewRuleBuilder(lib)
	err := rb.BuildRuleFromResource("MyKnowledge", "0.0.1", pkg.NewBytesResource([]byte(MyBusinessRule)))
```

When you want to add additional rule entries,

```go
	// do not recreate new knowledge base...
	// use your original instance of knowledge library...
	// lib := ast.NewKnowledgeLibrary()
	// Reuse mylib

	rb := builder.NewRuleBuilder(mylib )
	err := rb.BuildRuleFromResource("MyKnowledge", "0.0.1", pkg.NewBytesResource([]byte(MoreBusinessRuleToAdd)))	
```

as long as you use the same rule name and version, It will add the rule to that rulename and version.

## Removing `RuleEntry`-es from an already existing `KnowledgeLibrary`
 
Simply get the KnowledgeBase from the library, and remove RuleEntry by its name.
RuleEntry is simply stored as map in KnowledgeBase.

```go
	kb := mylib.GetKnowledgeBase("MyKnowledge", "0.0.1")
	kb.RemoveRuleEntry("ruleName")
```

This will remove the rule from blueprint, as shown in [this snippet](https://github.com/hyperjumptech/grule-rule-engine/blob/436f654cf4accfe35dc9e06808820775cc3e00ee/ast/KnowledgeBase.go#L153). 

## Updating speciffic RuleEntry(ies)

Once you see a change of your rule in the database. For each of the changed rule, you should remove those changed rules (as explained above) from KnowledgeLibrary. Once done, reconstruct DRL for those changed rules only, no need to construct other unchanged rules. And add them back into the KnowledgeLibrary (as also explained above).

# Is it safe to modify rules on the running production engine ?

Well, For save bet, you can do 2 approach. 

- Not recommended. To create a mutex in your server, to ensure no thread is accessing the knowledge base while you add/modify/remove rule-entries in a knowledge base.
- Recommended. Rebuild your rule on the same KnowledgeLibrary, you don't need to create another library, same but on a different version knowledgebase. Switch your rule engine lookup from old to new version. This is much safer, with tradeoff that, yes, its expensive. 
 
```go
err := rb.BuildRuleFromResource("MyKnowledge", "0.0.2", pkg.NewBytesResource([]byte(MoreBusinessRuleToAdd)))
```

e.g. Increase the version from `0.0.1` to `0.0.2`.

When done, simply use new version for all request. (currentVersion is the variable that store the version that you change)

```go
currentVersion := getVersionAfterAnyRuleEntryChange()
kb := lib.NewKnowledgeBaseInstance("MyKnowledge", currentVersion )
```

Why is it recommended ? Because thats what KnowledgeBase name and version are for. Its how Drools team do it.

I hope this help.

**Comment by newm4n** [comment]
> Thanks for the quick reply
> 
> yes i see `AddRuleEntry` and `RemoveRuleEntry` for `knowledgeBase.go`. I am able to add/remove a rule entry to the existing knowledgeBase.
> 
> Example:
> 
> ```go
> 	rule4 = `
> rule AgeNameCheck3 "test 2"  salience 10{
>     when
>       Pogo.Compare(User.Name, "Vasu")  
>     then
>       User.Name = "Success vasu";
>       Log(User.Name);
>       Retract("AgeNameCheck");
> }
> `
> 
> 	is := antlr.NewInputStream(rule4)
> 	lexer := parser.Newgrulev3Lexer(is)
> 	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)
> 
> 	var parseError error
> 	errCall := func(e error) {
> 		parseError = e
> 	}
> 
> 	listener := antlr2.NewGruleV3ParserListener(kb, errCall)
> 
> 	psr := parser.Newgrulev3Parser(stream)
> 	psr.BuildParseTrees = true
> 	antlr.ParseTreeWalkerDefault.Walk(listener, psr.Grl())
> 
> 	grl := listener.Grl
> 	for _, ruleEntry := range grl.RuleEntries {
> 		kb.RemoveRuleEntry(ruleEntry.RuleName)
> 		err := kb.AddRuleEntry(ruleEntry)
> 		if err != nil && err.Error() != "rule entry TestNoDesc already exist" {
> 			fmt.Printf("warning while adding rule entry : %s. got %s, possibly already added by antlr listener", ruleEntry.RuleName, err.Error())
> 		}
> 	}
> 
> 	kb.WorkingMemory.IndexVariables()
> ```
> 
> where kb is the existing knowledgebase.
> 
> Yes the above code is working fine for me to add a rule entry (removing it first for safer side). Let me know is this a right way to do ?

Yes, you're correct. The KB should be the KnowledgeBase you get from library using `GetKnowledgeBase` method. NOT `NewKnowledgeBaseInstance` method.  The first method will get the blueprint. The second method will return the copy from the blueprint and wont get persisted into the library if changed. The blueprint will.

**Comment by vasubabu-Sixt** [comment]
Yes @newm4n , thank you very much.

```go
	// do not recreate new knowledge base...
	// use your original instance of knowledge library...
	// lib := ast.NewKnowledgeLibrary()
	// Reuse mylib

	rb := builder.NewRuleBuilder(mylib )
	err := rb.BuildRuleFromResource("MyKnowledge", "0.0.1", pkg.NewBytesResource([]byte(MoreBusinessRuleToAdd)))	
```

one question btw, lets say a knowledgeBase `kb` having a rule1 already and now using your way i am adding one more rule entry (rule2), does kb will have only one rule entry (rule2), what i am expecting is rule2 and rule 1.

I have tried your example for adding new rule entries and what i see is only one rule entry. let me know if you need more info.

**Comment by jinagamvasubabu** [comment]
Yes @newm4n , thank you very much.

```go
	// do not recreate new knowledge base...
	// use your original instance of knowledge library...
	// lib := ast.NewKnowledgeLibrary()
	// Reuse mylib

	rb := builder.NewRuleBuilder(mylib )
	err := rb.BuildRuleFromResource("MyKnowledge", "0.0.1", pkg.NewBytesResource([]byte(MoreBusinessRuleToAdd)))	
```

one question btw, lets say a knowledgeBase `kb` having a rule1 already and now using your way i am adding one more rule entry (rule2), does kb will have only one rule entry (rule2), what i am expecting is rule2 and rule 1.

I have tried your example for adding new rule entries and what i see is only one rule entry. let me know if you need more info.

**Comment by newm4n** [comment]
I made a simple test and it worked as expected.
https://github.com/newm4n/grule-rule-engine/blob/1d115f9e4a2a44e8c95c277271b3a129b2a25ed5/examples/RuleMod_test.go

**Comment by vasubabu-Sixt** [comment]
Thanks, this works. This is a great help and much appreciated

Its my bad, i got to know the issue i was not doing this 
`	knowledgeBase = knowledgeLibrary.NewKnowledgeBaseInstance("Test", "0.0.1")` 
after i added a new rule which leads to Knowledgebase returns only one rule entry.

**Comment by jinagamvasubabu** [comment]
Thanks, this works. This is a great help and much appreciated

Its my bad, i got to know the issue i was not doing this 
`	knowledgeBase = knowledgeLibrary.NewKnowledgeBaseInstance("Test", "0.0.1")` 
after i added a new rule which leads to Knowledgebase returns only one rule entry.
