### ISSUE TITLE
Cashflow example and rule retraction

### ISSUE THREAD

**Issue by mgilbir** [hyperjumptech/grule-rule-engine#268]
**Describe the bug**
When I run the cashflow example the result doesn't reflect what logically the test example is trying to showcase: that you can have another object to accumulate output from multiple runs.
When the `SumUpPurchase` rule is retracted, it is effectively forcing that only the first purchase is accumulated in the `CashFlow` object.

**To Reproduce**
Run `go test examples -run TestCashFlowCalculator_CalculatePurchases -v`

There are 11 purchases passed but the cashflow object string output that is the test result shows:
```
=== RUN   TestCashFlowCalculator_CalculatePurchases
Purchase count 1 total amount 100000.000000. Total tax are 115000.000000 thus total cash in 215000.000000
```

**Expected behavior**
The cashflow object to reflect the multiple purchases that have been processed.

**Comment by newm4n** [comment]
This is really odd, and strangely afterall this time, this never caught by anybody. Thanks a lot @mgilbir .
This is due to whenever the engine start using previously used KnowledgeBase, it never reset all retracted rules. 
The function is already created to reset all retracted rules, but some how, never called.

I've made an adjustment in my branch, and its ok now. About to PR it.

**Comment by newm4n** [comment]
Fixed in new release https://github.com/hyperjumptech/grule-rule-engine/releases/tag/v1.10.3

**Comment by mgilbir** [comment]
Confirmed that it works now. Thanks for the quick fix!
