### ISSUE TITLE
how to get current rule name?

### ISSUE THREAD

**Issue by kennir** [hyperjumptech/grule-rule-engine#276]
**Is your feature request related to a problem? Please describe.**
I want to get the name of the current RULE in the context

**Describe the solution you'd like**

```
rule nameHere "a sample rule" salience 0 {
    when
        ctx.HasResult("ok") == false
    then
        ctx.SetReuslt("ok") 
}
```

I want the SetResult can retrieve the name of the rule, which should be "nameHere" here

**Describe alternatives you've considered**

**Additional context**

**Comment by fangminyu** [comment]
@kennir For most of our usual cases, we define drool by ourselves. In other word, rule name is pre-defined and known. Hence It can be easily solved by following:


```
rule nameHere "a sample rule" salience 0 {
    when
        ctx.HasResult("ok") == false
    then
        ctx.SetReuslt("nameHere") 
}
```

**Comment by tpihl** [comment]
I understand that this may be the best we can do at the moment but it's not good, and make me reach for some templating tool to run on the rules on top of everything else (and I KNOW thats a really bad idea, things a complex enough).

A huge percentage of our customers rules have most of their content copied and pasted from other rules. Already today to make sure a rulename is unique is a mess, now hoping the developer/ruleauthor to remember to change it in two places to the same thing. I think this path have a high probability become problematic where the customers/users perception would be "bad ruleengine" even though it isn't.

Most of us like go because it tries to help us avoid traps, any maybe some other solution could be done to cover several of these cases.

Maybe possible to register a function that will get called at the end of the application of a rule with access to rule metadata as well as the data object(s). If it gets that access though a passed ref to a struct, that struct could have methods to easily and controlled be able to use Calls to Changed(), Retract() or Complete() based available data.

Would make it really simple to avoid adding a Retact("runeName") in every rule that looks for problems and should not be reevaluated unless there is another go-around.

Also for every rule that use a helper to evaluate or calculate a value, to "behind the scenes" treat this helper method as volatile or how to phrase it.

Another way would of course to add naming conventions that adds magic sauce in the mix but i really don't like that

Any opinions?

**Comment by mvberg** [comment]
> now hoping the developer/ruleauthor to remember to change it in two places to the same thing

this is my biggest concern with the suggested approach - duplication / typos.

> Would make it really simple to avoid adding a Retact("runeName") in every rule

For this use case, I've worked around this by attaching a [GruleEngineListener](https://github.com/hyperjumptech/grule-rule-engine/blob/master/engine/GruleEngineListener.go) to the `Engine` instance and performing the `ReactactRule(entry.RuleName)` on the `KnowledgeBase` in the `ExecuteRuleEntry` callback.

But, as far as I understand it, that callback happens [before](https://github.com/hyperjumptech/grule-rule-engine/blob/master/engine/GruleEngine.go#L204) execution ..

I do think it would be helpful to be able to access some type of "context" about the [RuleEntry](https://github.com/hyperjumptech/grule-rule-engine/blob/master/ast/RuleEntry.go#L38) in GRL itself (inside the `when` and `then` blocks) ...
