### ISSUE TITLE
Is rule versioning or rule history supported/achieved?

### ISSUE THREAD

**Issue by DevDiva1** [hyperjumptech/grule-rule-engine#42]
Is Rule versioning supported or can it be achieved?
For instance - A case from the past can be re-assessed using the rules that were applicable in the period that the case deals with.

**Comment by agan83** [comment]
How to update or delete rules dynamically？

**Comment by newm4n** [comment]
Hi DevDiva1, 

Thanks for trying Grule, Im sorry, I don't really get your question. I will try to answer, I hope I got it right. Grule don't really handling rule versioning. Since GRL them self is only text, you could easily use versioning software to maintain them such as GIT. The "version" in the knowledge base is a merely an annotation to help user to know what version number of rule set being loaded into it, it has nothing to do with actual version control. Grule however, can load rule directly from GIT.

agan83,

Also thank you for trying Grule,
For removing rule entry, The KnowledgeBase has the following function exactly for this purpose. `KnowledgeBase.RemoveRuleEntry(name string)` function will remove Rule entry from a KnowledgeBase.

To update a rule entry in KnowledgeBase, first you have to remove it using `KnowledgeBase.RemoveRuleEntry(name string)` and then add another entry using the builder into the existing KnowledgeBase. 

if you want to temporary deactivate a rule from  within  `KnowledgeBase` from within your rule, you could use `Retract` function.

**Comment by DevDiva1** [comment]
This helps, thank you!

**Comment by chestarss** [comment]
delete(klib.Library, fmt.Sprintf("%s:%s", ruleName, ruleVersion))
