### ISSUE TITLE
 rule Execute()?

### ISSUE THREAD

**Issue by jingc1413** [hyperjumptech/grule-rule-engine#61]
hi, thanks.
How do I know which specific rule was successfully or failed executed?
Can it be returned by the execute function?

**Comment by newm4n** [comment]
Hi jingc1413,

1. In rule engine context, this question might means 2 thing. If a rule is successfully selected for execution, or if the rule is selected, the execution went successful. For the former, the answer is you can implement the `EventHandler`. For the later, you could use `Log` function.
2. Executes return error which may caused by an error while calling functions from within the rule, by non-existent data in DataContext or if the rule evaluation cycle has reached its maximum.

**Comment by jingc1413** [comment]
ok, thanks
