### ISSUE TITLE
Support comparison string values

### ISSUE THREAD

**Issue by liouxiao** [hyperjumptech/grule-rule-engine#90]
I'm curious why not support comparison string values.

Here's an example rule:

```
rule CompareString "Comparison two string values" salience 10 {
    when 
        "A" < "B"
    then
        Retract("CompareString");
}
```

The error message is `can not use data type of string in LT comparison`.

Similar errors happened on `<=`(LTE), `>`(GT) and `>=`(GTE).

**Comment by newm4n** [comment]
While its actually easy to enhance Grule with string to string comparison, but first we need to establish what is the correct way of comparing string. Is it by its length. by lexicographical ?

Which should be lesser or greater or equal, ascending or descending ?
"A" vs "aa", "Aa" vs "aA", "a" vs "aaa", "   a" vs " ", "4" vs "41", "abc" vs "cba"

Once we settle with clear definition of string comparison, we can add the feature. And once its set, for future compatibility sake, we should never change it. Some language give a call back function for such implementation (function to be implemented by each developer to fit their own need), because the creator don't want string comparison get tied up to one implementation.  

For now, you can create your own custom function in your own fact for your own string to string comparison.

```go
type StringHelper struct {
}

func (sh *StringHelper) CompareLexical(a, b string) int { // 0 means equal, above 0 means greater, bellow means lesser
   ....
}
```

In your rule

```go
when 
   Helper.CompareLexical(Fact.StringA, "StringToCompare") <= 0
then
  ...
```

**Comment by liouxiao** [comment]
hi @newm4n , thanks for your example.

I do use a similar function to compare strings:

```
import "strings"

type Strings struct {
}
func (a *Strings) Compare(str1, str2 string) int {
	return strings.Compare(str1, str2)
}
```

and in rule

```
when
    Strings.Compare("A", "B") < 0
then
   ...
```

But I still think it's not such straightforward, why not just use the same logic as "strings.Compare()" in Golang? 

Golang's built-in string comparison operators include ==, !=, <, >, <=, >=, which should be good for comparing two strings lexicographically, e.g.

```
"A" < "aa"
"Aa" < "aA"
"a" < "aaa"
" a" > " "
"4" < "41"
"abc" < "cba"
```

**Comment by liouxiao** [comment]
A quick fix (if takes Golang built-in string comparison operators) would be:

https://github.com/hyperjumptech/grule-rule-engine/compare/master...liouxiao:issue-90

**Comment by newm4n** [comment]
Wow.... I did the same.

[my master vs branch compare](https://github.com/hyperjumptech/grule-rule-engine/compare/master...newm4n:feat/stringcompare)

While yours using straight operator, `vara > varb`
Mine is using `strings.Compare(vara, varb) > 0`

You know what. I like your changes better because straight comparison operator usage might be faster as its probably done straight by the compiler. While strings.Compare were done throught stdlib. 
More on that, your approach are tightly couple with the language. 

Can I request 1 thing, could you take my test approach ? I think, my test could give better string comparison coverage, as each comparison will validate all operators. When its done, I will merge your PR ASAP.

**Comment by liouxiao** [comment]
@newm4n , I merged your test case, all tests passed, here's my PR:

https://github.com/hyperjumptech/grule-rule-engine/pull/91
