### ISSUE TITLE
Question: ANTLR listener or visitor?

### ISSUE THREAD

**Issue by liouxiao** [hyperjumptech/grule-rule-engine#92]
hi, @newm4n , current Grule takes listener-pattern, I'd like to know is there any consideration for that?

e.g. https://stackoverflow.com/questions/20714492/antlr4-listeners-and-visitors-which-to-implement mentioned:

> There's another important difference between these two patterns: a visitor uses the call stack to manage tree traversals, whereas the listener uses an explicit stack allocated on the heap, managed by a walker. This means that **large inputs to a visitor could blow out the stack**, while a listener would have no trouble.

**Comment by newm4n** [comment]
While visitor pattern may seems shorter and simpler, in its development I find it not so simple especially when you want to ensure NO AST graph duplication, which will have direct impact on performance. Duplicated syntax, functions, variables is a no-no. When you see duplication, you make sure that theres only one instance exist. Well, Rule Engine implementations are on the race for "who's the fastest", and some algorithm even never get out to open source domain because its one of the selling point. 

To give you perspective, try read the Grule documentation about RETE. You will see even multiple rule uses same syntax. but underneath it, it uses only one graph. For functions, and expressions. 

With listener, ANTLR4 separates between entering the AST node and exiting, When an exit occurred we can look for duplication of graph tree. I don't know how to do this with Visitor pattern.

In grule, the GRL DSL were translated into AST graph first. When all rule AST are loaded, it then executed toward Fact set. When constructing AST graph, I find it easier, for me, to use listener pattern, and the exit functions enables me to find graph duplication. Its automatic. 

If we write the GRL parsing using visitor pattern, the parsing operation it self is considered executing the rule. Values are evaluated straight away. Very convenience to write an interpreter. Theres a parsing penalty when running the rule.  Grule is a bit different. Ast graph need to be constructed before hand, prior execution. So adding rule into knowledge base (the parsing) may be a bit costly, but once executed, its just like an object tree.

I hope my explanation answer your query. If you think Visitor pattern would work better for Grule, Im open for advises.

**Comment by liouxiao** [comment]
Thanks! 

It makes a lot of sense.

Another question: when converting ANTLR to AST, did you manually write the AST code, or use a builder tool?

**Comment by newm4n** [comment]
ANTLR4 build its internal AST Contexts. But this internal graph only to help listener implementor to inspect the grammar, texts, etc. Thus, for my purpose, I created my own AST nodes and graph. I don't know if theres any AST builder for Golang though.
